import { ICustomers } from "../interface";

export const customers: ICustomers[] = [
  {
    id: "1",
    name: "Jane Cooper",
    firstname: "Jane",
    lastname: "Cooper",
    company: "Apple",
    email: "jessica.hanson@example.com",
    password: "example123",
    admin: true,
  },
  {
    id: "2",
    name: "Guy Hawkins",
    firstname: "Guy",
    lastname: "Hawkins",
    company: "IBM",
    email: "bill.sanders@example.com",
    password: "0717example",
    admin: true,
  },
  {
    id: "3",
    name: "Jenny Wilson",
    firstname: "Jenny",
    lastname: "Wilson",
    company: "Gillette",
    email: "georgia.young@example.com",
    password: "07example",
    admin: false,
  },
  {
    id: "4",
    name: "Robert Fox",
    firstname: "Robert",
    lastname: "Fox",
    company: "Ferrari",
    email: "sara.cruz@example.com",
    password: "example111",
    admin: true,
  },
  {
    id: "5",
    name: "Cody Fisher",
    firstname: "Cody",
    lastname: "Fisher",
    company: "Starbucks",
    email: "jakson.graham@example.com",
    password: "rof1yev111",
    admin: true,
  },
  {
    id: "6",
    name: "Albert Flores",
    firstname: "Albert",
    lastname: "Flores",
    company: "Nintendo",
    email: "tanya.hill@example.com",
    password: "08188800af",
    admin: false,
  },
];
